name: Build

on:
  push:
    branches:
      - main
      - next-major

  pull_request:
    branches:
      - '*'

jobs:
  check-style:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Global cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: cargo-ubuntu-latest-stable-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-ubuntu-latest-stable

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Format check
        run: cargo fmt -- --check

      - name: Static analysis
        run: cargo clippy

  test:
    needs: check-style
    timeout-minutes: 20

    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
          - beta
          - nightly

    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Global cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: cargo-${{ matrix.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-${{ matrix.os }}-${{ matrix.rust }}

      - name: Target Cache
        uses: actions/cache@v2
        with:
          path: ./target
          key: target-${{ matrix.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: |
            target-${{ matrix.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}
            target-${{ matrix.os }}-${{ matrix.rust }}

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev libasound2-dev

      - name: Run tests
        run: cargo test --workspace

  wasm-check:
    needs: check-style
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Global cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: cargo-ubuntu-latest-stable-wasm-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-ubuntu-latest-stable-wasm

      - name: Target Cache
        uses: actions/cache@v2
        with:
          path: ./target
          key: target-ubuntu-latest-stable-wasm-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: |
            target-ubuntu-latest-stable-wasm-${{ hashFiles('**/Cargo.toml') }}
            target-ubuntu-latest-stable-wasm

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Check WASM
        run: cargo check --workspace --target wasm32-unknown-unknown

  ignored-tests:
    needs: [ check-style, test ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Global cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: cargo-ubuntu-latest-stable-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-ubuntu-latest-stable

      - name: Target Cache
        uses: actions/cache@v2
        with:
          path: ./target
          key: target-ubuntu-latest-stable-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: |
            target-ubuntu-latest-stable-${{ hashFiles('**/Cargo.toml') }}
            target-ubuntu-latest-stable

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev libasound2-dev

      - name: Run ignored tests
        run: cargo test --workspace -- --ignored
