name: Build

on:
  push:
    branches:
      - main

jobs:
  publish:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Global cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: cargo-ubuntu-latest-stable-wasm-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: cargo-ubuntu-latest-stable-wasm

      - name: Target Cache
        uses: actions/cache@v2
        with:
          path: ./target
          key: target-ubuntu-latest-stable-wasm-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: |
            target-ubuntu-latest-stable-wasm-${{ hashFiles('**/Cargo.toml') }}
            target-ubuntu-latest-stable-wasm

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: wasm-pack build --no-typescript --target web --release

      - name: Prepare files
        run: |
          mkdir -p site/pkg
          mv pkg/polar_clock.js site/pkg/
          mv pkg/polar_clock_bg.wasm site/pkg/
          mv index.html site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
